<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('cars')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $vehicles = [
            // carsNow
            [
                'plate_number' => '51A-00001',
                'name' => 'VINFAST LUX SA 2.0 2021',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1150000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 3',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Flash Sale',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00002',
                'name' => 'Vinfast VF7 2024',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1170000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 10',
                'seats' => 5,
                'fuel' => 'Điện',
                'tag' => 'Giảm 10%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00003',
                'name' => 'Ford Everest 2024',
                'brand' => 'Ford',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1620000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 3',
                'seats' => 7,
                'fuel' => 'Dầu',
                'tag' => 'Giảm 10%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00004',
                'name' => 'Kia Carens 2023',
                'brand' => 'Kia',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1080000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận Bình Thạnh',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Giảm 10%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00005',
                'name' => 'Mitsubishi Xpander 2023',
                'brand' => 'Mitsubishi',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 810000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Thành phố Thủ Đức',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Flash Sale',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // suggestCars
            [
                'plate_number' => '51A-00006',
                'name' => 'Toyota Vios 2024',
                'brand' => 'Toyota',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 860000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 7',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Nổi bật',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00007',
                'name' => 'Hyundai Accent 2024',
                'brand' => 'Hyundai',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 900000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=900&q=80',
                'location' => 'Tân Bình',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Hot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00008',
                'name' => 'Mazda CX5 2024',
                'brand' => 'Mazda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1380000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=900&q=80',
                'location' => 'Phú Nhuận',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Ưu đãi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00009',
                'name' => 'Kia Seltos 2024',
                'brand' => 'Kia',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1040000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=900&q=80',
                'location' => 'Gò Vấp',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Mới',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // luxuryCars
            [
                'plate_number' => '51A-00010',
                'name' => 'Mercedes C300 2024',
                'brand' => 'Mercedes',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 2710000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 8',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Xe xịn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00011',
                'name' => 'Mercedes GLC 200 2022',
                'brand' => 'Mercedes',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 2710000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 8',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Xe xịn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00012',
                'name' => 'Kia Carnival 2025',
                'brand' => 'Kia',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 2830000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 8',
                'seats' => 7,
                'fuel' => 'Khác',
                'tag' => 'Xe xịn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51A-00013',
                'name' => 'BMW 320i 2024',
                'brand' => 'BMW',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 3090000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 1',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Xe xịn',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // extraBrandCars - VinFast
            [
                'plate_number' => '51B-1001',
                'name' => 'VinFast VF e34 2022',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 980000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 3',
                'seats' => 5,
                'fuel' => 'Điện',
                'tag' => 'Giảm 12%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1002',
                'name' => 'VinFast VF5 2023',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 860000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 10',
                'seats' => 5,
                'fuel' => 'Điện',
                'tag' => 'Flash Sale',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1003',
                'name' => 'VinFast VF6 2024',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1190000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
                'location' => 'Bình Thạnh',
                'seats' => 5,
                'fuel' => 'Điện',
                'tag' => 'Mới',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1004',
                'name' => 'VinFast Lux A 2.0 2021',
                'brand' => 'VinFast',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 1320000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Thủ Đức',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Ưu đãi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1005',
                'name' => 'VinFast Lux SA 2.0 2022',
                'brand' => 'VinFast',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1540000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 8',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Hot',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mitsubishi
            [
                'plate_number' => '51B-1101',
                'name' => 'Mitsubishi Xpander 2023',
                'brand' => 'Mitsubishi',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 850000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=900&q=80',
                'location' => 'Gò Vấp',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Sale',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1102',
                'name' => 'Mitsubishi Attrage 2022',
                'brand' => 'Mitsubishi',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 690000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 7',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Tiết kiệm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1103',
                'name' => 'Mitsubishi Triton 2024',
                'brand' => 'Mitsubishi',
                'type' => 'Pickup',
                'transmission' => 'Số tự động',
                'price_per_day' => 1230000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',
                'location' => 'Tân Bình',
                'seats' => 5,
                'fuel' => 'Dầu',
                'tag' => 'Mạnh mẽ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1104',
                'name' => 'Mitsubishi Outlander 2021',
                'brand' => 'Mitsubishi',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1160000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=80',
                'location' => 'Phú Nhuận',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Gia đình',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1105',
                'name' => 'Mitsubishi Pajero Sport 2022',
                'brand' => 'Mitsubishi',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1490000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 2',
                'seats' => 7,
                'fuel' => 'Dầu',
                'tag' => 'Cao cấp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Toyota
            [
                'plate_number' => '51B-1201',
                'name' => 'Toyota Vios 2024',
                'brand' => 'Toyota',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 760000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 1',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Phổ biến',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1202',
                'name' => 'Toyota Corolla Cross 2024',
                'brand' => 'Toyota',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1180000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 3',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Mới',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1203',
                'name' => 'Toyota Camry 2023',
                'brand' => 'Toyota',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 1360000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=900&q=80',
                'location' => 'Bình Thạnh',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Sedan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1204',
                'name' => 'Toyota Fortuner 2022',
                'brand' => 'Toyota',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1590000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 9',
                'seats' => 7,
                'fuel' => 'Dầu',
                'tag' => 'SUV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1205',
                'name' => 'Toyota Innova 2021',
                'brand' => 'Toyota',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1090000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80',
                'location' => 'Thủ Đức',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => '7 chỗ',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hyundai
            [
                'plate_number' => '51B-1301',
                'name' => 'Hyundai Accent 2024',
                'brand' => 'Hyundai',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 740000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Tân Phú',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Tiện lợi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1302',
                'name' => 'Hyundai Elantra 2023',
                'brand' => 'Hyundai',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 960000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 5',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Sedan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1303',
                'name' => 'Hyundai Creta 2024',
                'brand' => 'Hyundai',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1140000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Gò Vấp',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'SUV đô thị',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1304',
                'name' => 'Hyundai Tucson 2022',
                'brand' => 'Hyundai',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1410000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 2',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Hot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1305',
                'name' => 'Hyundai Santa Fe 2023',
                'brand' => 'Hyundai',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1680000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 7',
                'seats' => 7,
                'fuel' => 'Dầu',
                'tag' => 'Gia đình',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kia
            [
                'plate_number' => '51B-1401',
                'name' => 'Kia Morning 2023',
                'brand' => 'Kia',
                'type' => 'Hatchback',
                'transmission' => 'Số tự động',
                'price_per_day' => 620000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 10',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Giá tốt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1402',
                'name' => 'Kia K3 2024',
                'brand' => 'Kia',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 910000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=900&q=80',
                'location' => 'Phú Nhuận',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Sedan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1403',
                'name' => 'Kia Seltos 2024',
                'brand' => 'Kia',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1080000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=900&q=80',
                'location' => 'Bình Thạnh',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'SUV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1404',
                'name' => 'Kia Carens 2023',
                'brand' => 'Kia',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1190000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 12',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => '7 chỗ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1405',
                'name' => 'Kia Carnival 2024',
                'brand' => 'Kia',
                'type' => 'MPV',
                'transmission' => 'Số tự động',
                'price_per_day' => 2190000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 1',
                'seats' => 7,
                'fuel' => 'Dầu',
                'tag' => 'Cao cấp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mazda
            [
                'plate_number' => '51B-1501',
                'name' => 'Mazda 2 2023',
                'brand' => 'Mazda',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 760000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 11',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Nhỏ gọn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1502',
                'name' => 'Mazda 3 2024',
                'brand' => 'Mazda',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 950000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
                'location' => 'Tân Bình',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Sedan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1503',
                'name' => 'Mazda CX-3 2024',
                'brand' => 'Mazda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1090000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 4',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'SUV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1504',
                'name' => 'Mazda CX-5 2023',
                'brand' => 'Mazda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1340000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 7',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Hot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1505',
                'name' => 'Mazda CX-8 2022',
                'brand' => 'Mazda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1620000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Thủ Đức',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => '7 chỗ',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Honda
            [
                'plate_number' => '51B-1601',
                'name' => 'Honda City 2024',
                'brand' => 'Honda',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 820000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 6',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Bán chạy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1602',
                'name' => 'Honda Civic 2023',
                'brand' => 'Honda',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 1180000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 1',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Sedan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1603',
                'name' => 'Honda HR-V 2024',
                'brand' => 'Honda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1260000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 9',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'SUV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1604',
                'name' => 'Honda CR-V 2023',
                'brand' => 'Honda',
                'type' => 'SUV',
                'transmission' => 'Số tự động',
                'price_per_day' => 1540000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Bình Thạnh',
                'seats' => 7,
                'fuel' => 'Xăng',
                'tag' => 'Gia đình',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plate_number' => '51B-1605',
                'name' => 'Honda Accord 2022',
                'brand' => 'Honda',
                'type' => 'Sedan',
                'transmission' => 'Số tự động',
                'price_per_day' => 1450000,
                'status' => 'available',
                'image_url' => 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=80',
                'location' => 'Quận 2',
                'seats' => 5,
                'fuel' => 'Xăng',
                'tag' => 'Cao cấp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('cars')->insert($vehicles);
    }
}